name: Release Jar

on:
  push:
    branch: ["main"]
  pull_request:
    branch: ["main"]


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.10'

      - name: Check version Gradle
        run: gradle --version

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Print to console END
        run: echo END TODO release