name: Release Jar

on:
  push:
    branches:
      - main



jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get latest tag
        id: get_tag
        run: |
            git fetch --tags
            latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next version
        id: version
        run: |
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "Next version: $new_tag"

      - name: Create new git tag
        run: |
          git tag $new_tag
          git push origin $new_tag 

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.10'

      - name: Check version Gradle
        run: gradle --version

      - name: Set up Gradle wrapper
        run: gradle wrapper --gradle-version=8.10

      - name: Grant execute permission for Gradle and build .jar
        run: | 
          chmod +x gradlew
          ./gradlew clean build

      - name: Get commit log
        id: chengelog
        run: |
          git fetch --tags
          if git rev-parse ${{ env.latest_tag }} >/dev/null 2>&1; then
            log=$(git log ${{ env.latest_tag }}..HEAD --oneline)
          else
            log=$(git log --oneline)
          fi
          echo "log<<EOF" >> $GITHUB_ENV
          echo "$log" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_tag }}
          name: "Release ${{ env.new_tag }}"
          body: |
            Автоматический релиз с ветки main.
            Коммиты с последнего тега:
            
            ${{ env.log }}
          files: build/libs/*.jar
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
